description: >
  CircleCI's base image as default executor
docker:
  - image: <<parameters.image>>:<<parameters.tag>>

parameters:
  image:
    description: The name of image
    default: cimg/base
    type: string
  tag:
    description: The image version tag
    default: stable
    type: string
